version: "3.9"

services:
  database:
    image: postgres
    container_name: pg_car_checkup
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=car_checkup
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: api_car_checkup
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local